# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install LibreOffice for file conversion
RUN apk add --no-cache libreoffice

WORKDIR /app

# Copy package and TypeScript config
COPY package.json tsconfig.json ./
# Copy source files
COPY src ./src

# Install dependencies and build
RUN npm install && npm run build && npm prune --production

# Set entrypoint to start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
